#!/usr/bin/env bash
# change user to nginx
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
