#!/usr/bin/env bash
# Install and configure haproxy.

# update system
sudo apt update
# install haproxy
sudo apt install haproxy -y
load_balance_config=\
"frontend haproxy_inbound
        bind *:80
        default_backend haproxy_httpd
backend haproxy_httpd
        balance roundrobin
        server 4808-web-01 54.163.68.20
        server 4808-web-02 54.226.116.83
"
# add the new configuration to the the haproxy.conf file
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg
echo $load_balance_config >> /etc/haproxy/haproxy.cfg
