#!/usr/bin/env bash
# Script that install nginx server and write content to the root.
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www/html
echo "Holberton School for the win!" > /var/www/html/index.html
