#!/usr/bin/env bash
# script that install nginx and configure it to redirect to another page when
# accessing the /redirect_me page.
sudo apt update -y
sudo apt install nginx -y
# store content to be written

new_config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
               root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        location /redirect_me { 
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}
"
# put the the redirect configuration after the server_name directive
# sudo sed -i "/server_name _;/a $content" /etc/nginx/sites-available/default
# sudo sed -i "/server_name _;/a $content" /etc/nginx/sites-enabled/default
echo "$new_config" > /etc/nginx/sites-available/default
sudo service nginx restart